### ISSUE TITLE
N++ crashes when XPath expression string ends with "/"

### ISSUE THREAD

**Issue by bojler41** [morbac/xmltools#96]
When XPath expression = /SOMENODE - it evaluates expression correctly
When XPath expression = /SOMENODE/ - it crashes N++

3.1.1.2 64bit version plugin
N++ 7.9.3 64bit

It would be best to catch this case and act more nicely than crashing.

P.S. An improvement suggestion - It'd be really nice to either add [ENTER] button action on the XPath expression field in the Evaluate XPath expression window to launch an evaluation and not to be forced to use the mouse to click the Evaluate button or introduce some keyboard shortcuts to the window.

Thank you!

**Comment by morbac** [comment]
Unfortunalely I couldn't make N++ crash when using `/SOMENODE/` expression. During my tests, I always get an error message, but no crash:
![image](https://user-images.githubusercontent.com/10232771/110248055-871f3980-7f6f-11eb-83e1-c701c44794f6.png)

Your suggestion about ENTER action is good. I tried to add it, but I currently cannot do it unless I change the dialog to a modal one. It seems there is some limitations on handling TAB and ENTER keys in modelless dialog. I'll try further to find a solution.

Regards

**Comment by bojler41** [comment]
This one works ok
![image](https://user-images.githubusercontent.com/77965111/110255393-b647a200-7f93-11eb-8beb-624e6d6205ed.png)


This one crashes N++ without any notice - the screenshot is taken right after clicking Evaluate button but just a few seconds before the crash itself.
![image](https://user-images.githubusercontent.com/77965111/110255484-58678a00-7f94-11eb-891e-5179be020f1e.png)
You can click again anywhere on the N++ or the plugin popup window (during these few seconds) so you can see the mouse icon changing to a whirling circle (kind of "I am working" icon) and you know that the window/process is not responding.


This is my list of plugins (maybe there's something which interacts with another...)
![image](https://user-images.githubusercontent.com/77965111/110255346-784a7e00-7f93-11eb-8537-ff6093adc56b.png)


As for the "ENTER suggestion" - if this is not possible then is it possible to use shortcuts for the Evaluate, Copy and Clear buttons?

**Comment by morbac** [comment]
Sorry, but I'm really not able to reproduce the issue, even after having installed same extensions than you

**Comment by rdipardo** [comment]
Reproducible without any additional plugins:

![Screenshot 2021-04-11 020206](https://user-images.githubusercontent.com/59004801/114294106-848e9300-9a8b-11eb-94fb-481c9c2bbd51.png)

Tested with the same markup as in the OP's example, and a few other files, all with the same result.

~~~
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.867
Current ANSI codepage : 1252
Plugins : XMLTools.dll 
~~~

**Comment by morbac** [comment]
As mentionned in issue #123, I just released the [version 3.1.1.9](https://github.com/morbac/xmltools/releases/tag/3.1.1.9) which fix a memory allocation issue which is responsible of NPP crash. With this new release I get no crash and following behaviour:
![image](https://user-images.githubusercontent.com/10232771/137333095-7a806f48-c42a-4809-943f-67ede193d1e6.png)
Do you still have NPP crash with this new version ?

**Comment by bojler41** [comment]
Mee to. Crash after testing with 3.1.1.9 XMLTools-3.1.1.9-x64.zip on the N++ 8.1.5 (64-bit).

Notepad++ v8.1.5   (64-bit)
Build time : Sep 26 2021 - 15:23:23
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1237
Current ANSI codepage : 1250
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppBplistPlugin.dll NppConverter.dll nppcrypt.dll NppExport.dll XMLTools.dll

**Comment by AikenBM** [comment]
Yeah, I still get a crash. Although this time I get two error log entries from the same crash.

This is the older one:

```
Log Name:      Application
Source:        Application Error
Date:          10/19/2021 8:28:06 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      REDACTED
Description:
Faulting application name: notepad++.exe, version: 8.1.6.0, time stamp: 0x6162d91a
Faulting module name: XMLTools.dll, version: 3.1.1.10, time stamp: 0x61687d1f
Exception code: 0xc0000005
Fault offset: 0x00000000000157a3
Faulting process id: 0x4ae8
Faulting application start time: 0x01d7c4e4ac4de528
Faulting application path: C:\Program Files\Notepad++\notepad++.exe
Faulting module path: C:\Program Files\Notepad++\plugins\XMLTools\XMLTools.dll
Report Id: 94c51c7b-cc48-4848-aa00-b6a8e19ec8be
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-19T12:28:06.1144212Z" />
    <EventRecordID>16186</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>REDACTED</Computer>
    <Security />
  </System>
  <EventData>
    <Data>notepad++.exe</Data>
    <Data>8.1.6.0</Data>
    <Data>6162d91a</Data>
    <Data>XMLTools.dll</Data>
    <Data>3.1.1.10</Data>
    <Data>61687d1f</Data>
    <Data>c0000005</Data>
    <Data>00000000000157a3</Data>
    <Data>4ae8</Data>
    <Data>01d7c4e4ac4de528</Data>
    <Data>C:\Program Files\Notepad++\notepad++.exe</Data>
    <Data>C:\Program Files\Notepad++\plugins\XMLTools\XMLTools.dll</Data>
    <Data>94c51c7b-cc48-4848-aa00-b6a8e19ec8be</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

And this is the newer one:

```
Log Name:      Application
Source:        Application Error
Date:          10/19/2021 8:28:06 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      REDACTED
Description:
Faulting application name: notepad++.exe, version: 8.1.6.0, time stamp: 0x6162d91a
Faulting module name: XMLTools.dll, version: 3.1.1.10, time stamp: 0x61687d1f
Exception code: 0xc000041d
Fault offset: 0x00000000000157a3
Faulting process id: 0x4ae8
Faulting application start time: 0x01d7c4e4ac4de528
Faulting application path: C:\Program Files\Notepad++\notepad++.exe
Faulting module path: C:\Program Files\Notepad++\plugins\XMLTools\XMLTools.dll
Report Id: fa9cc3ed-ca3d-41b7-b69c-2ff0df230655
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-19T12:28:06.6430211Z" />
    <EventRecordID>16187</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>REDACTED</Computer>
    <Security />
  </System>
  <EventData>
    <Data>notepad++.exe</Data>
    <Data>8.1.6.0</Data>
    <Data>6162d91a</Data>
    <Data>XMLTools.dll</Data>
    <Data>3.1.1.10</Data>
    <Data>61687d1f</Data>
    <Data>c000041d</Data>
    <Data>00000000000157a3</Data>
    <Data>4ae8</Data>
    <Data>01d7c4e4ac4de528</Data>
    <Data>C:\Program Files\Notepad++\notepad++.exe</Data>
    <Data>C:\Program Files\Notepad++\plugins\XMLTools\XMLTools.dll</Data>
    <Data>fa9cc3ed-ca3d-41b7-b69c-2ff0df230655</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

And here's the Notepad++ debug info:

```
Notepad++ v8.1.6   (64-bit)
Build time : Oct 10 2021 - 14:10:29
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 
```

**Comment by bojler41** [comment]
> Ok, I just released a [new version of xmltools 3.1.1.10](https://github.com/morbac/xmltools/releases/tag/3.1.1.10). Please tell me if it's ok now.

Just tested. No crash. It works! Thank you!
